So that's what that's for
 Error:  Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.7.10:compile (compile) on project elijah-prolific-remnant: Compilation failure: Compilation failure:
Error:  /home/runner/.m2/repository/com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0.jar!/META-INF/okio.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
Error:  /home/runner/.m2/repository/com/squareup/okio/okio/3.6.0/okio-3.6.0.jar!/META-INF/okio.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
Error:  -> [Help 1]